name:                flipstone-prelude
version:             0.1.1.0
github:              "flipstone/flipstone-prelude"
license:             MIT
author:              "Flipstone Technology Partners"
maintainer:          "github@flipstone.com"
copyright:           "2021 Flipstone Technology Partners"

extra-source-files:
  - README.md
  - ChangeLog.md

default-extensions:
  - CPP
  - NoImplicitPrelude

description:         Please see the README on GitHub at <https://github.com/flipstone/flipstone-prelude#readme>

dependencies:
  - base >= 4.7 && < 5
  - either
  - type-errors

flags:
  debug:
    description: Exposes debugging functions for use in development environments.
    manual: true
    default: false

library:
  source-dirs: src
  when:
    - condition: flag(debug)
      cpp-options: -DDEBUG
